### PR TITLE
Upgrading Docusaurus dependencies

### PR DESCRIPTION
**Pull request by nate-droid**
This PR should bump the docusaurus version by 2. The intention is to slowly start chipping away at all of the dependabot alerts.

### CODE REVIEW

**Review by olliefr — APPROVED** [review]
Moar security! ❤️

**Comment by benmarsden** [comment]
Can dependabot not auto-submit PRs to do this for us?

**Comment by nate-droid** [comment]
@benmarsden I did some research on the vulns, and they do not affect Docusaurus directly, so I was able to make an exception for those vulns. So regardless of this upgrade, the alerts shouldn't be spamming us every PR now 😄

**Review by jlarfors — APPROVED** [review]
LGTM

**Pull request merged**
