### PR TITLE
Add version command to Bubbly CLI

### PR DESCRIPTION
**Pull request by olliefr**
I have just finished watching a workshop on Go, and while trying out some ideas accidentally implemented the `version` command for Bubbly CLI:

```bash
./build/bubbly version
```
```
bubbly version undefined 4ab0314473f46af7a6a4de3db4587799897f4434
```

The `undefined` stands for Git tag, which the current commit does not have.

It's a very light-touch PR, I have not modified any existing code, apart from pruning some less than helpful comments from `env` package. And updated the `Makefile` a bit.

I can't see how this would adversely affect any part of Bubbly but if you disagree, please feel free to shoot down the PR :shipit: 

UPDATE: I've also updated the Dockerfiles to make it build _static_ binaries (`CGO_ENABLED=0`) for inclusion into the Docker image. This opens up using `static` versions of `distroless` images, something that the comment in the Dockerfile claimed we were doing, but actually weren't as our Bubbly binary was actually dynamically linked. This improves the situation because now the action is not in a disagreement with the documented intent. Goreleaser has been set up to build static images from the very beginning.

### CODE REVIEW

**Comment by jlarfors** [comment]
Thanks, it has annoyed me a few times to not have a `version` command :)

How does this play with `goreleaser`? Seems like it only affects things if we build using `make`?

**Comment by olliefr** [comment]
That is very true! I'll update the goreleaser config.

**Comment by olliefr** [comment]
I've created issue #141 which includes some documentation on our current build process and offers some ideas for improvement. That note was inspired by my work on this PR - I hope it is going to save someone time in the future, when bringing our build system to production quality.

**Comment by jlarfors** [comment]
Closing this as it has been added to the new version of bubbly (coming soon!)

**Pull request closed without merging**
